// Code generated by "stringer -type=WhiteBalanceT"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[wbUndefined-0]
	_ = x[wbAuto-1]
	_ = x[wbIndoor-2]
	_ = x[wbOutdoor-3]
	_ = x[wbOnePush-4]
	_ = x[wbManual-5]
	_ = x[wbOutdoorAuto-6]
	_ = x[wbSodiumLampAuto-7]
	_ = x[wbSodiumAuto-8]
}

const _WhiteBalanceT_name = "wbUndefinedwbAutowbIndoorwbOutdoorwbOnePushwbManualwbOutdoorAutowbSodiumLampAutowbSodiumAuto"

var _WhiteBalanceT_index = [...]uint8{0, 11, 17, 25, 34, 43, 51, 64, 80, 92}

func (i WhiteBalanceT) String() string {
	if i < 0 || i >= WhiteBalanceT(len(_WhiteBalanceT_index)-1) {
		return "WhiteBalanceT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WhiteBalanceT_name[_WhiteBalanceT_index[i]:_WhiteBalanceT_index[i+1]]
}
